apiVersion: v1
kind: Service
metadata:
  name: chain-client-solana-solana-server-501
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: chain-client-solana-solana-501
  type: ClusterIP
  ports:
    - protocol: TCP
      name: chain-client-solana-solana-api-501
      port: 9100
      targetPort: 9100
---
# Source: chain-client-solana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-client-solana-solana-501
  namespace: {{ .Release.Namespace }}
  labels:
    app: chain-client-solana-solana-501
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-client-solana-solana-501
  template:
    metadata:
      labels:
        app: chain-client-solana-solana-501
    spec:
      containers:
        - name: chain-client-solana-solana-501
          image: otmoic/chainclient-solana:V2.1.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 800Mi
          ports:
            - containerPort: 9100
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "chain-client-status-report-solana"
            - name: CHAIN_TYPE
              value: "evm"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: SYSTEM_CHAIN_ID
              value: "501"
            - name: CHAIN_ID
              value: "501"
            - name: OS_API_KEY
              value: {{ .Values.os.appKey }}
            - name: OS_API_SECRET
              value: {{ .Values.os.appSecret }}
            - name: OS_SYSTEM_SERVER
              value: system-server.user-system-{{ .Values.bfl.username }}
            - name: CONTRACT_ADDRESS
              value: "FAqaHQHgBFFX8fJB6fQUqNdc8zABV5pGVRdCt7fLLYVo"
            - name: START_BLOCK
              value: "276713741"
            - name: RPC_URL
              value: "https://billowing-palpable-model.solana-mainnet.quiknode.pro/d67a99e94835f1c1356b32cd1a5111dc74c59919/"
            - name: LOAD_RPC_URLS
              value: "https://lb.drpc.org/ogrpc?network=solana&dkey=AhGF-xa9e0C7uWvXRQ-Y5Eh_P_pnQo0R76rxUgWAgP__|50,https://billowing-palpable-model.solana-mainnet.quiknode.pro/d67a99e94835f1c1356b32cd1a5111dc74c59919/|50"
            - name: START_TOP_HEIGHT
              value: 'true'
            - name: AUTO_START
              value: 'false'
            - name: FEE_RECEPIENT
              value: 'Gexuvyazbb48d5U6voRna5ef1SLPRUNLiwavqEx8otgy'
            - name: CONCURRENCY
              value: '3'
            - name: FETCHERS_SIZE
              value : '2'
