# Service configuration
apiVersion: v1
kind: Service
metadata:
  name: chain-client-solana-solana-server-501
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: chain-client-solana-solana-501
  type: ClusterIP
  ports:
    - protocol: TCP
      name: nginx-proxy-port
      port: 9100
      targetPort: 80
---
# Multi-container deployment with inline nginx config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-client-solana-solana-501
  namespace: {{ .Release.Namespace }}
  labels:
    app: chain-client-solana-solana-501
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-client-solana-solana-501
  template:
    metadata:
      labels:
        app: chain-client-solana-solana-501
    spec:
      containers:        
        # Message producer container
        - name: message-producer
          image: docker.io/magicpigdocker/images:chainclient-25-0.1
          imagePullPolicy: Always
          command: ["ts-node"]
          args: ["src/message-producer/index.ts"]
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_DB_NUMBER 
              value: "0"
            - name: STATUS_KEY
              value: "chain-client-status-report-solana"
            - name: CHAIN_ID
              value: "501"
            - name: MESSAGE_PRODUCER_PORT
              value: "3001"
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: MONGODB_ACCOUNT
              value: {{ .Values.mongodb.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_PORT
              value: "{{ .Values.mongodb.port }}"
            - name: MONGODB_DBNAME_LP_STORE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: MONGODB_AUTH_SOURCE
              value: {{ .Values.mongodb.databases.lp_store }}
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 800Mi

        # Monitor container
        - name: monitor
          image: docker.io/magicpigdocker/images:chainclient-25-0.1
          imagePullPolicy: Always
          command: ["ts-node"]
          args: ["src/monitor/index.ts"]
          ports:
            - containerPort: 3002
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_DB_NUMBER 
              value: "0"
            - name: STATUS_KEY
              value: "chain-client-status-report-solana"
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: MONGODB_ACCOUNT
              value: {{ .Values.mongodb.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_PORT
              value: "{{ .Values.mongodb.port }}"
            - name: MONGODB_DBNAME_LP_STORE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: MONGODB_AUTH_SOURCE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: MONITOR_NAME
              value: chain-client-solana-solana-501-monitor
            - name: LOGGER_LEVEL
              value: "debug"
            - name: SYSTEM_CHAIN_ID
              value: "501"
            - name: CHAIN_ID
              value: "501"
            - name: OBRIDGE_CONTRACT
              value: "0x6F12FED6Cd5BeBFA3351c447f7873B76178B1b84"
            - name: RPCS
              value: "https://api.testnet.solana.com"
            - name: RPC_TIMEOUT
              value: "30000"
            - name: BLOCK_MARGIN
              value: "3"
            - name: BLOCK_MODE_SWITCH_THRESHOLD
              value: "50"
            - name: BLOCK_INTERVAL
              value: "3000"
            - name: BATCH_SIZE
              value: "5000"
            - name: N8N_WEBHOOK_URL
              value: "http://n8n.edge-dev.xyz/webhook/f8b3f611-89b9-4128-8e93-b50ff8903531"
            - name: ADMIN_SERVICE_URL
              value: "http://lpnode-admin-server:18006"
            - name: ADMIN_SERVICE_POLLING_INTERVAL
              value: "15000"
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 800Mi

        # Public service container
        - name: public-service
          image: docker.io/magicpigdocker/images:chainclient-25-0.1
          imagePullPolicy: Always
          command: ["ts-node"]
          args: ["src/public-service/index.ts"]
          ports:
            - containerPort: 3003
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_DB_NUMBER 
              value: "0"
            - name: STATUS_KEY
              value: "chain-client-status-report-solana"
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: MONGODB_ACCOUNT
              value: {{ .Values.mongodb.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_PORT
              value: "{{ .Values.mongodb.port }}"
            - name: MONGODB_DBNAME_LP_STORE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: MONGODB_AUTH_SOURCE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: MONITOR_NAME
              value: chain-client-solana-solana-501-monitor
            - name: PUBLIC_SERVICE_PORT
              value: "3003"
            - name: CHAIN_ID
              value: "501"
            - name: LOGGER_LEVEL
              value: "debug"
            - name: SYSTEM_CHAIN_ID
              value: "501"
            - name: N8N_WEBHOOK_URL
              value: "http://n8n.edge-dev.xyz/webhook/f8b3f611-89b9-4128-8e93-b50ff8903531"
            - name: ADMIN_SERVICE_URL
              value: "http://lpnode-admin-server:18006"
            - name: ADMIN_SERVICE_POLLING_INTERVAL
              value: "15000"
            - name: RPCS
              value: "https://api.testnet.solana.com"
            - name: RPC_TIMEOUT
              value: "30000"
            - name: RELAY_WALLET
              value: "false"
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 800Mi

        # Sender container
        - name: sender
          image: docker.io/magicpigdocker/images:chainclient-25-0.1
          imagePullPolicy: Always
          command: ["ts-node"]
          args: ["src/sender/index.ts"]
          ports:
            - containerPort: 3004
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_DB_NUMBER 
              value: "0"
            - name: STATUS_KEY
              value: "chain-client-status-report-solana"
            - name: ADMIN_SERVICE_URL
              value: "http://lpnode-admin-server:18006"
            - name: ADMIN_SERVICE_POLLING_INTERVAL
              value: "15000"
            - name: CHAIN_ID
              value: "501"
            - name: MONITOR_NAME
              value: chain-client-solana-solana-501-monitor
            - name: SENDER_RPC_URL
              value: "https://api.testnet.solana.com"
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: MONGODB_ACCOUNT
              value: {{ .Values.mongodb.username }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password }}
            - name: MONGODB_PORT
              value: "{{ .Values.mongodb.port }}"
            - name: MONGODB_DBNAME_LP_STORE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: MONGODB_AUTH_SOURCE
              value: {{ .Values.mongodb.databases.lp_store }}
            - name: SENDER_SERVICE_PORT
              value: "3004"
            - name: SYSTEM_CHAIN_ID
              value: "501"
            - name: RELAY_WALLET
              value: "false"
            - name: TX_TIMEOUT
              value: "30000"
            - name: N8N_WEBHOOK_URL
              value: "http://n8n.edge-dev.xyz/webhook/f8b3f611-89b9-4128-8e93-b50ff8903531"
            - name: LOGGER_LEVEL
              value: "debug"
            - name: OBRIDGE_CONTRACT
              value: "0x6F12FED6Cd5BeBFA3351c447f7873B76178B1b84"
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 800Mi

        # Nginx proxy container
        - name: nginx-proxy
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: 100m
              memory: 56Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: nginx-config
          configMap:
            name: chain-client-solana-solana-server-501-nginx-conf
---
# Inline ConfigMap definition
apiVersion: v1
kind: ConfigMap
metadata:
  name: chain-client-solana-solana-server-501-nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;

            # Message Producer endpoints
            location ~ ^/producer/getNextEvent {
                proxy_pass http://localhost:3001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location ~ ^/producer/getLatestEvent {
                proxy_pass http://localhost:3001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Public Service endpoints
            location ~ ^/solana-client-[0-9]+/lpnode/get_wallets {
                proxy_pass http://localhost:3003;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location ~ ^/solana-client-[0-9]+/lpnode/get_wallet_balances {
                proxy_pass http://localhost:3003;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Sender endpoints
            location = /submitTokenTransfer {
                proxy_pass http://localhost:3004;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location ~ "/queryJobStatus/[a-f0-9]+" {
                proxy_pass http://localhost:3004;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Sender lpnode endpoints
            location ~ ^/solana-client-[0-9]+/lpnode/(transfer_in|confirm|refund|sign_message) {
                proxy_pass http://localhost:3004;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # Default fallback route
            location / {
                return 404;
            }
        }
    }