# Service definition for otmoic-chain-client-solana-solana-server
---
apiVersion: v1
kind: Service
metadata:
  name: otmoic-chain-client-solana-solana-server-501
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: otmoic-chain-client-solana-solana-501
  type: ClusterIP
  ports:
    - protocol: TCP
      name: otmoic-chain-client-solana-solana-api-501
      port: 9100
      targetPort: 9100

# Deployment definition for otmoic-chain-client-solana-solana-501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otmoic-chain-client-solana-solana-501
  namespace: {{ .Release.Namespace }}
  labels:
    app: otmoic-chain-client-solana-solana-501
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otmoic-chain-client-solana-solana-501
  template:
    metadata:
      labels:
        app: otmoic-chain-client-solana-solana-501
    spec:
      containers:
      - name: otmoic-chain-client-solana-solana-501
        image: otmoic/chainclient-solana:ebd453c2
        ports:
          - containerPort: 9100
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 1024Mi
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: otmoic-relay-db-redis
                key: redis-password
          - name: EVM_CLIENT_PORT
            value: "9100"
          - name: REDIS_HOST
            value: "otmoic-relay-db-redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: RPC_URL
            value: "https://solana-devnet.g.alchemy.com/v2/0nfhMHYlkNm3BrBpJDiIuMoEab-qZbF8"
          - name: CONTRACT_ADDRESS
            value: "FAqaHQHgBFFX8fJB6fQUqNdc8zABV5pGVRdCt7fLLYVo"
          - name: SYSTEM_CHAIN_ID
            value: "501"
          - name: CHAIN_ID
            value: "501"
          - name: START_BLOCK
            value: "306012670"
          - name: SERVER_URL_TRANSFER_OUT
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_out"
          - name: SERVER_URL_TRANSFER_IN
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_in"
          - name: SERVER_URL_CONFIRM
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_confirm"
          - name: SERVER_URL_REFUNDED
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_refunded"
          - name: AUTO_START
            value: 'true'
          - name: RELAY_WALLET_ADDRESS
            value: '2CPdcUk3qfXaCZqDHZce941NJAMokSsYgsvEo9Ku5uvS'
          - name: RELAY_WALLET_PRIVATE_KEY
            value: 'DZzHqRkAqCgkxGqeggEXCtYzMRr4QS3wQ56Xe69mfkvCgYQXF1eFQkTxrunDFZXJdqYpDwjUf6WULnwzxvHeJJe'
          - name: RELAY_WALLET
            value: 'true'
          - name: START_TOP_HEIGHT
            value: 'true'
          - name: FEE_RECEPIENT
            value: '8os21rmBjg63xMWuRK4vza3DxZ69AoQD6SffBBmnrpiQ'