# Source: otmoic-chain-client-near/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: otmoic-chain-client-near-server-397
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: otmoic-chain-client-near-397
  type: ClusterIP
  ports:
    - protocol: TCP
      name: otmoic-chain-client-near-api-397
      port: 9100
      targetPort: 9100
---
# Source: otmoic-chain-client-near/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otmoic-chain-client-near-397
  namespace: {{ .Release.Namespace }}
  labels:
    app: otmoic-chain-client-near-397
spec:
  replicas: 0
  selector:
    matchLabels:
      app: otmoic-chain-client-near-397
  template:
    metadata:
      labels:
        app: otmoic-chain-client-near-397
    spec:
      containers:
      - name: otmoic-chain-client-near-397
        image: otmoic/chainclient-near:Test-V2.1.2
        resources:
          requests:
            cpu: 1m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
          - containerPort: 9100
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: otmoic-relay-db-redis
                key: redis-password
          - name: NEAR_CLIENT_PORT
            value: "9100"
          - name: REDIS_HOST
            value: "otmoic-relay-db-redis-master"
          - name: CONTRACT_ADDRESS
            value: "otv1.saidev.testnet"
          - name: SYSTEM_CHAIN_ID
            value: "397"
          - name: START_BLOCK
            value: "158672019"
          - name: LAKE_BUCKET
            value: "near-lake-data-testnet"
          - name: LAKE_REGION
            value: "eu-central-1"
          - name: LAKE_POOLSIZE
            value: "3"
          - name: CONNECTION_NETWORKID
            value: "testnet"
          - name: CONNECTION_NODEURL
            value: "https://rpc.testnet.near.org"
          - name: CONNECTION_WALLETURL
            value: "https://wallet.testnet.near.org"
          - name: CONNECTION_HELPERURL
            value: "https://helper.testnet.near.org"
          - name: CONNECTION_EXPLORERURL
            value: "https://explorer.testnet.near.org"
          - name: AWS_ACCESS_KEY_ID
            value: ""
          - name: AWS_SECRET_ACCESS_KEY
            value: ""
          - name: SERVER_URL_TRANSFER_OUT
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_out"
          - name: SERVER_URL_TRANSFER_IN
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_transfer_in"
          - name: SERVER_URL_CONFIRM
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_confirm"
          - name: SERVER_URL_REFUNDED
            value: "http://otmoicrelay-server:9102/relay/chain_client/on_refunded"
          - name: TOKEN_MAP
            value: "{\"otmoic-test-tokena.testnet\":{\"receiver_id\":\"0xc46adbee202892c5c989d515763a575bce534fa09c8bb4a13bcd7289a516e97b\"}}"
