apiVersion: v1
data:
  config.toml: |
    n8nUrl = ""
    restartInterval = 43200000 # 1000 * 60 * 60 * 12

    [point]
    port = 1235
    arbiterUrl = "http://arbiter-service:1236"
    relayAdminUrl = "http://relay-adminpanel-service:9101"
    refreshInterval = 43200000 # 1000 * 60 * 60 * 12

    [arbiter]
    didSupportUrl = "https://did-support.ursa-services.bttcdn.com/graphql"
    port = 1236

    [agent]
    port = 1237
    rpc = "https://mainnet.optimism.io"
    priv = ""
    contractAddr = "0x3179CE5fAB68C0286Da85f3d61BcE7116815e799"

    [connector]
    port = 1234
    callbackUrl = "http://connector-service:1234"

    [chainIdConvert]
    9006 = "56"
    614 = "10"
    501 = "501"


    [[chainClients]]
    url = "http://otmoic-chain-client-evm-bsc-server-9006:9100"
    historyUrl = "http://otmoic-chain-client-evm-bsc-server-9006:9100"
    initBlockHeight = 40172800
    chainId = "9006" # bsc
    nativeChainId = "56" # bsc testnet
    registerPath = "/support/register"
    historyPath = "/support/history"

    [[chainClients]]
    url = "http://otmoic-chain-client-evm-opt-server-614:9100"
    historyUrl = "http://otmoic-chain-client-evm-opt-server-614:9100"
    initBlockHeight = 122239818
    chainId = "614" # opt
    nativeChainId = "10" # opt testnet
    registerPath = "/support/register"
    historyPath = "/support/history"

    [[chainClients]]
    url = "http://otmoic-chain-client-solana-solana-server-501:9100"
    historyUrl = "otmoic-chain-client-solana-solana-history-server-501:9100"
    initBlockHeight = 277643113
    chainId = "501" # solana
    nativeChainId = "501" # solana mainnet
    registerPath = "/support/register"
    historyPath = "/support/history"

kind: ConfigMap
metadata:
  name: reputation-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: reputation-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reputation-connector
  template:
    metadata:
      labels:
        app: reputation-connector
    spec:
      containers:
        - name: connector
          image: otmoic/reputation-suite:V2.1.2
          env:
          - name: DBUSER
            value: "postgres"
          - name: DBHOST
            value: "otmoic-relay-db-postgresql-postgresql-ha-pgpool"
          - name: DBPORT
            value: "5432"
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: otmoic-relay-db-postgresql-postgresql-ha-postgresql
                key: password
          ports:
            - containerPort: 1234
          volumeMounts:
          - name: reputation-config
            mountPath: /src/config.toml
            subPath: config.toml
          command: ['npm', 'run', 'start-connector']
          resources: 
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: reputation-config
          configMap:
            name: reputation-config
            defaultMode: 438
            items:
            - key: config.toml
              path: config.toml
          
---
apiVersion: v1
kind: Service
metadata:
  name: connector-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: reputation-connector
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbiter-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: reputation-arbiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reputation-arbiter
  template:
    metadata:
      labels:
        app: reputation-arbiter
    spec:
      containers:
        - name: arbiter
          image: otmoic/reputation-suite:V2.1.2
          env:
          - name: DBUSER
            value: "postgres"
          - name: DBHOST
            value: "otmoic-relay-db-postgresql-postgresql-ha-pgpool"
          - name: DBPORT
            value: "5432"
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: otmoic-relay-db-postgresql-postgresql-ha-postgresql
                key: password
          ports:
            - containerPort: 1236
          volumeMounts:
          - name: reputation-config
            mountPath: /src/config.toml
            subPath: config.toml
          command: ['npm', 'run', 'start-arbiter']
          resources: 
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: reputation-config
          configMap:
            name: reputation-config
            defaultMode: 438
            items:
            - key: config.toml
              path: config.toml
          
---
apiVersion: v1
kind: Service
metadata:
  name: arbiter-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: reputation-arbiter
  ports:
    - protocol: TCP
      port: 1236
      targetPort: 1236
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: points-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: reputation-points
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reputation-points
  template:
    metadata:
      labels:
        app: reputation-points
    spec:
      containers:
        - name: points
          image: otmoic/reputation-suite:V2.1.2
          env:
          - name: DBUSER
            value: "postgres"
          - name: DBHOST
            value: "otmoic-relay-db-postgresql-postgresql-ha-pgpool"
          - name: DBPORT
            value: "5432"
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: otmoic-relay-db-postgresql-postgresql-ha-postgresql
                key: password
          ports:
            - containerPort: 1235
          volumeMounts:
          - name: reputation-config
            mountPath: /src/config.toml
            subPath: config.toml
          command: ['npm', 'run', 'start-points']
          resources: 
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: reputation-config
          configMap:
            name: reputation-config
            defaultMode: 438
            items:
            - key: config.toml
              path: config.toml
          
---
apiVersion: v1
kind: Service
metadata:
  name: points-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: reputation-points
  ports:
    - protocol: TCP
      port: 1235
      targetPort: 1235
---

  
